### ISSUE TITLE
[BUG] Incorrect discovery of Proto package names with underscore

### ISSUE THREAD

**Issue by eliasdarruda** [eigr/spawn#314]
**Describe the bug**
For the given protobuf:

```
syntax = "proto3";

package tickets.forms.user_form;

message UserFormState {
	string id = 1;
}
```

The package will resolve incorrectly from the descriptor meta:

```
** (UndefinedFunctionError) function Tickets.Forms.Userform.UserFormState.decode/1 is undefined (module Tickets.Forms.Userform.UserFormState is not available)
    Tickets.Forms.Userform.UserFormState.decode("")
    (spawn 1.1.1) lib/spawn/utils/any_serializer.ex:28: Spawn.Utils.AnySerializer.unpack_unknown/1
    (spawn_sdk 1.1.1) lib/system/spawn_system.ex:132: SpawnSdk.System.SpawnSystem.invoke/2
    (tickets 0.1.0) lib/tickets_web/live/user_live/user_live.ex:23: TicketsWeb.UserLive.handle_event/3
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/channel.ex:507: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 1.2.1) /home/dev/workspace/escala/tickets/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/channel.ex:260: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
    (stdlib 4.0.1) gen_server.erl:1197: :gen_server.handle_msg/6
    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

It was supposed to be

Tickets.Forms.User**F**orm.UserFormState.decode

instead it is

Tickets.Forms.User**f**orm.UserFormState.decode

**Comment by sleipnir** [comment]
Closed by #315
