### ISSUE TITLE
high demand requests fail update state

### ISSUE THREAD

**Issue by sleipnir** [eigr/spawn#39]
**Describe the bug**

```
022-09-08 17:41:40.035 [spawn@127.0.0.1]:[pid=<0.982.0> ]:[debug]:Terminating actor zezinho with reason {:function_clause, [{Actors.Actor.Entity, :update_state, [%Actors.Actor.Entity.EntityState{actor: %Eigr.Functions.Protocol.Actors.Actor{__unknown_fields__: [], deactivate_strategy: nil, name: "zezinho", persistent: false, snapshot_strategy: nil, state: nil}, state_hash: nil, system: %Eigr.Functions.Protocol.Actors.ActorSystem{__unknown_fields__: [], name: "spawn-system", registry: %Eigr.Functions.Protocol.Actors.Registry{__unknown_fields__: [], actors: %{"zezinho" => %Eigr.Functions.Protocol.Actors.Actor{__unknown_fields__: [], deactivate_strategy: %Eigr.Functions.Protocol.Actors.ActorDeactivateStrategy{__unknown_fields__: [], strategy: {:timeout, %Eigr.Functions.Protocol.Actors.TimeoutStrategy{__unknown_fields__: [], timeout: 50000}}}, name: "zezinho", persistent: true, snapshot_strategy: %Eigr.Functions.Protocol.Actors.ActorSnapshotStrategy{__unknown_fields__: [], strategy: {:timeout, %Eigr.Functions.Protocol.Actors.TimeoutStrategy{__unknown_fields__: [], timeout: 10000}}}, state: %Eigr.Functions.Protocol.Actors.ActorState{__unknown_fields__: [], state: nil, tags: %{}}}}}}}, %Eigr.Functions.Protocol.Context{__unknown_fields__: [], state: %Google.Protobuf.Any{__unknown_fields__: [], type_url: "type.googleapis.com/io.eigr.spawn.example.MyState", value: <<8, 168, 44>>}}], [file: 'lib/actors/actor/entity.ex', line: 512]}, {Actors.Actor.Entity, :handle_call, 3, [file: 'lib/actors/actor/entity.ex', line: 232]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 721]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 750]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}
2022-09-08 17:41:40.035 [spawn@127.0.0.1]:[pid=<0.982.0> ]:[error]:GenServer {Spawn.Cluster.Node.Registry, {Actors.Actor.Entity, "zezinho"}} terminating
** (FunctionClauseError) no function clause matching in Actors.Actor.Entity.update_state/2
    (actors 0.1.0) lib/actors/actor/entity.ex:512: Actors.Actor.Entity.update_state(%Actors.Actor.Entity.EntityState{actor: %Eigr.Functions.Protocol.Actors.Actor{__unknown_fields__: [], deactivate_strategy: nil, name: "zezinho", persistent: false, snapshot_strategy: nil, state: nil}, state_hash: nil, system: %Eigr.Functions.Protocol.Actors.ActorSystem{__unknown_fields__: [], name: "spawn-system", registry: %Eigr.Functions.Protocol.Actors.Registry{__unknown_fields__: [], actors: %{"zezinho" => %Eigr.Functions.Protocol.Actors.Actor{__unknown_fields__: [], deactivate_strategy: %Eigr.Functions.Protocol.Actors.ActorDeactivateStrategy{__unknown_fields__: [], strategy: {:timeout, %Eigr.Functions.Protocol.Actors.TimeoutStrategy{__unknown_fields__: [], timeout: 50000}}}, name: "zezinho", persistent: true, snapshot_strategy: %Eigr.Functions.Protocol.Actors.ActorSnapshotStrategy{__unknown_fields__: [], strategy: {:timeout, %Eigr.Functions.Protocol.Actors.TimeoutStrategy{__unknown_fields__: [], timeout: 10000}}}, state: %Eigr.Functions.Protocol.Actors.ActorState{__unknown_fields__: [], state: nil, tags: %{}}}}}}}, %Eigr.Functions.Protocol.Context{__unknown_fields__: [], state: %Google.Protobuf.Any{__unknown_fields__: [], type_url: "type.googleapis.com/io.eigr.spawn.example.MyState", value: <<8, 168, 44>>}})
    (actors 0.1.0) lib/actors/actor/entity.ex:232: Actors.Actor.Entity.handle_call/3
    (stdlib 3.17) gen_server.erl:721: :gen_server.try_handle_call/4
    (stdlib 3.17) gen_server.erl:750: :gen_server.handle_msg/6
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.980.0>): {:invocation_request, %Eigr.Functions.Protocol.InvocationRequest{__unknown_fields__: [], actor: %Eigr.Functions.Protocol.Actors.Actor{__unknown_fields__: [], deactivate_strategy: nil, name: "zezinho", persistent: false, snapshot_strategy: nil, state: nil}, async: false, command_name: "sum", system: %Eigr.Functions.Protocol.Actors.ActorSystem{__unknown_fields__: [], name: "spawn-system", registry: %Eigr.Functions.Protocol.Actors.Registry{__unknown_fields__: [], actors: %{"zezinho" => %Eigr.Functions.Protocol.Actors.Actor{__unknown_fields__: [], deactivate_strategy: %Eigr.Functions.Protocol.Actors.ActorDeactivateStrategy{__unknown_fields__: [], strategy: {:timeout, %Eigr.Functions.Protocol.Actors.TimeoutStrategy{__unknown_fields__: [], timeout: 50000}}}, name: "zezinho", persistent: true, snapshot_strategy: %Eigr.Functions.Protocol.Actors.ActorSnapshotStrategy{__unknown_fields__: [], strategy: {:timeout, %Eigr.Functions.Protocol.Actors.TimeoutStrategy{__unknown_fields__: [], timeout: 10000}}}, state: %Eigr.Functions.Protocol.Actors.ActorState{__unknown_fields__: [], state: nil, tags: %{}}}}}}, value: %Google.Protobuf.Any{__unknown_fields__: [], type_url: "type.googleapis.com/io.eigr.spawn.example.MyBusinessMessage", value: <<8, 168, 44>>}}}
State: %Actors.Actor.Entity.EntityState{actor: %Eigr.Functions.Protocol.Actors.Actor{__unknown_fields__: [], deactivate_strategy: nil, name: "zezinho", persistent: false, snapshot_strategy: nil, state: nil}, state_hash: nil, system: %Eigr.Functions.Protocol.Actors.ActorSystem{__unknown_fields__: [], name: "spawn-system", registry: %Eigr.Functions.Protocol.Actors.Registry{__unknown_fields__: [], actors: %{"zezinho" => %Eigr.Functions.Protocol.Actors.Actor{__unknown_fields__: [], deactivate_strategy: %Eigr.Functions.Protocol.Actors.ActorDeactivateStrategy{__unknown_fields__: [], strategy: {:timeout, %Eigr.Functions.Protocol.Actors.TimeoutStrategy{__unknown_fields__: [], timeout: 50000}}}, name: "zezinho", persistent: true, snapshot_strategy: %Eigr.Functions.Protocol.Actors.ActorSnapshotStrategy{__unknown_fields__: [], strategy: {:timeout, %Eigr.Functions.Protocol.Actors.TimeoutStrategy{__unknown_fields__: [], timeout: 10000}}}, state: %Eigr.Functions.Protocol.Actors.ActorState{__unknown_fields__: [], state: nil, tags: %{}}}}}}}
Client #PID<0.980.0> is alive

    (stdlib 3.17) gen.erl:233: :gen.do_call/4
    (elixir 1.13.1) lib/gen_server.ex:1027: GenServer.call/3
    (actors 0.1.0) lib/actors.ex:112: Actors.invoke/4
    (proxy 0.1.0) lib/proxy/routes/api.ex:35: anonymous fn/2 in Proxy.Routes.API.do_match/4
    (proxy 0.1.0) lib/plug/router.ex:246: anonymous fn/4 in Proxy.Routes.API.dispatch/2
    (telemetry 1.1.0) /home/sleipnir/workspaces/eigr/spawn/deps/telemetry/src/telemetry.erl:320: :telemetry.span/3
    (proxy 0.1.0) lib/plug/router.ex:242: Proxy.Routes.API.dispatch/2
    (proxy 0.1.0) lib/proxy/routes/api.ex:1: Proxy.Routes.API.plug_builder_call/2
2022-09-08 17:41:40.040 [spawn@127.0.0.1]:[pid=<0.980.0> ]:[error]:GenServer #PID<0.980.0> terminating
** (stop) exited in: GenServer.call({:via, Horde.Registry, {Spawn.Cluster.Node.Registry, {Actors.Actor.Entity, "zezinho"}}}, {:invocation_request, %Eigr.Functions.Protocol.InvocationRequest{__unknown_fields__: [], actor: %Eigr.Functions.Protocol.Actors.Actor{__unknown_fields__: [], deactivate_strategy: nil, name: "zezinho", persistent: false, snapshot_strategy: nil, state: nil}, async: false, command_name: "sum", system: %Eigr.Functions.Protocol.Actors.ActorSystem{__unknown_fields__: [], name: "spawn-system", registry: %Eigr.Functions.Protocol.Actors.Registry{__unknown_fields__: [], actors: %{"zezinho" => %Eigr.Functions.Protocol.Actors.Actor{__unknown_fields__: [], deactivate_strategy: %Eigr.Functions.Protocol.Actors.ActorDeactivateStrategy{__unknown_fields__: [], strategy: {:timeout, %Eigr.Functions.Protocol.Actors.TimeoutStrategy{__unknown_fields__: [], timeout: 50000}}}, name: "zezinho", persistent: true, snapshot_strategy: %Eigr.Functions.Protocol.Actors.ActorSnapshotStrategy{__unknown_fields__: [], strategy: {:timeout, %Eigr.Functions.Protocol.Actors.TimeoutStrategy{__unknown_fields__: [], timeout: 10000}}}, state: %Eigr.Functions.Protocol.Actors.ActorState{__unknown_fields__: [], state: nil, tags: %{}}}}}}, value: %Google.Protobuf.Any{__unknown_fields__: [], type_url: "type.googleapis.com/io.eigr.spawn.example.MyBusinessMessage", value: <<8, 168, 44>>}}}, 30000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Actors.Actor.Entity.update_state/2
            (actors 0.1.0) lib/actors/actor/entity.ex:512: Actors.Actor.Entity.update_state(%Actors.Actor.Entity.EntityState{actor: %Eigr.Functions.Protocol.Actors.Actor{__unknown_fields__: [], deactivate_strategy: nil, name: "zezinho", persistent: false, snapshot_strategy: nil, state: nil}, state_hash: nil, system: %Eigr.Functions.Protocol.Actors.ActorSystem{__unknown_fields__: [], name: "spawn-system", registry: %Eigr.Functions.Protocol.Actors.Registry{__unknown_fields__: [], actors: %{"zezinho" => %Eigr.Functions.Protocol.Actors.Actor{__unknown_fields__: [], deactivate_strategy: %Eigr.Functions.Protocol.Actors.ActorDeactivateStrategy{__unknown_fields__: [], strategy: {:timeout, %Eigr.Functions.Protocol.Actors.TimeoutStrategy{__unknown_fields__: [], timeout: 50000}}}, name: "zezinho", persistent: true, snapshot_strategy: %Eigr.Functions.Protocol.Actors.ActorSnapshotStrategy{__unknown_fields__: [], strategy: {:timeout, %Eigr.Functions.Protocol.Actors.TimeoutStrategy{__unknown_fields__: [], timeout: 10000}}}, state: %Eigr.Functions.Protocol.Actors.ActorState{__unknown_fields__: [], state: nil, tags: %{}}}}}}}, %Eigr.Functions.Protocol.Context{__unknown_fields__: [], state: %Google.Protobuf.Any{__unknown_fields__: [], type_url: "type.googleapis.com/io.eigr.spawn.example.MyState", value: <<8, 168, 44>>}})
            (actors 0.1.0) lib/actors/actor/entity.ex:232: Actors.Actor.Entity.handle_call/3
            (stdlib 3.17) gen_server.erl:721: :gen_server.try_handle_call/4
            (stdlib 3.17) gen_server.erl:750: :gen_server.handle_msg/6
            (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    (elixir 1.13.1) lib/gen_server.ex:1030: GenServer.call/3
    (actors 0.1.0) lib/actors.ex:112: Actors.invoke/4
    (proxy 0.1.0) lib/proxy/routes/api.ex:35: anonymous fn/2 in Proxy.Routes.API.do_match/4
    (proxy 0.1.0) lib/plug/router.ex:246: anonymous fn/4 in Proxy.Routes.API.dispatch/2
    (telemetry 1.1.0) /home/sleipnir/workspaces/eigr/spawn/deps/telemetry/src/telemetry.erl:320: :telemetry.span/3
    (proxy 0.1.0) lib/plug/router.ex:242: Proxy.Routes.API.dispatch/2
    (proxy 0.1.0) lib/proxy/routes/api.ex:1: Proxy.Routes.API.plug_builder_call/2
    (plug 1.13.6) lib/plug.ex:168: Plug.forward/4
Last message: {:continue, :handle_connection} 
State: {%ThousandIsland.Socket{acceptor_id: "C6D0FDA72891", connection_id: "CF66FAD33985", read_timeout: :infinity, socket: #Port<0.114>, transport_module: ThousandIsland.Transports.TCP}, %{handler_module: Bandit.InitialHandler, plug: {Proxy.Router, []}, read_timeout: 60000}}
```

**Comment by sleipnir** [comment]
Reopen becuse this correction make state invalid

**Comment by sleipnir** [comment]
Close by recent updates
