### ISSUE TITLE
no process: the process is not alive or there's no process currently associated with the given name

### ISSUE THREAD

**Issue by sleipnir** [eigr/spawn#41]
**Describe the bug**

Apparently the Activators ignore the treatment of the actors' reactivation process, which provides that if an actor is not in Horde.Registry it will be reactivated on the node that has the host function record.

This did not occur in any test of direct invocation of an actor between the host function and the proxy, so the problem is only related to Activators

```
2022-09-10 17:49:30.537 [activator_rabbitmq@127.0.0.1]:[pid=<0.936.0> ]:[info]: Dispatching message to Actors [%{actor: "robert", command: "setLanguage"}]
2022-09-10 17:49:30.537 [activator_rabbitmq@127.0.0.1]:[pid=<0.936.0> ]:[debug]:Decoded event: %Google.Protobuf.Any{__unknown_fields__: [], type_url: "type.googleapis.com/io.eigr.functions.spawn.codebeambr.messages.Request", value: "\n\ahaskell"}
2022-09-10 17:49:30.538 [activator_rabbitmq@127.0.0.1]:[pid=<0.5994.0> ]:[debug]:Request for Activate Actor [robert] using command [setLanguage] with payload: %Google.Protobuf.Any{__unknown_fields__: [], type_url: "type.googleapis.com/io.eigr.functions.spawn.codebeambr.messages.Request", value: "\n\ahaskell"}
2022-09-10 17:49:30.538 [activator_rabbitmq@127.0.0.1]:[pid=<21279.2653.0> ]:[debug]:Actor robert reactivated. PID: #PID<0.2644.0>
2022-09-10 17:49:30.540 [activator_rabbitmq@127.0.0.1]:[pid=<0.5994.0> ]:[error]:GenServer #PID<0.5994.0> terminating
** (stop) exited in: GenServer.call({:via, Horde.Registry, {Spawn.Cluster.Node.Registry, {Actors.Actor.Entity, "robert"}}}, {:invocation_request, %Eigr.Functions.Protocol.InvocationRequest{__unknown_fields__: [], actor: %Eigr.Functions.Protocol.Actors.Actor{__unknown_fields__: [], deactivate_strategy: nil, name: "robert", persistent: false, snapshot_strategy: nil, state: nil}, async: false, command_name: "setLanguage", system: %Eigr.Functions.Protocol.Actors.ActorSystem{__unknown_fields__: [], name: "spawn-system", registry: nil}, value: %Google.Protobuf.Any{__unknown_fields__: [], type_url: "type.googleapis.com/io.eigr.functions.spawn.codebeambr.messages.Request", value: "\n\ahaskell"}}}, 30000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.13.1) lib/gen_server.ex:1019: GenServer.call/3 
    (actors 0.1.0) lib/actors.ex:112: Actors.invoke/4
    (activator 0.1.0) lib/activator/dispatcher/default_dispatcher.ex:48: anonymous fn/3 in Activator.Dispatcher.DefaultDispatcher.do_dispatch/3
    (flow 1.2.0) lib/flow/materialize.ex:758: anonymous fn/4 in Flow.Materialize.mapper/2
    (flow 1.2.0) lib/flow/materialize.ex:647: Flow.Materialize."-build_reducer/2-lists^foldl/2-0-"/3
    (flow 1.2.0) lib/flow/materialize.ex:647: anonymous fn/5 in Flow.Materialize.build_reducer/2
    (flow 1.2.0) lib/flow/map_reducer.ex:59: Flow.MapReducer.handle_events/3
    (gen_stage 1.1.2) lib/gen_stage.ex:2471: GenStage.consumer_dispatch/6
Last message: {:"$gen_consumer", {#PID<0.5993.0>, #Reference<0.3707952406.3645636609.244954>}, [%{actor: "robert", command: "setLanguage"}]}
State: {%{#Reference<0.3707952406.3645636609.244954> => nil}, %{done?: false, producers: %{#Reference<0.3707952406.3645636609.244954> => #PID<0.5993.0>}, trigger: #Function<2.15704490/3 in Flow.Window.Global.materialize/5>}, {0, 8}, [], #Function<6.70741094/4 in Flow.Materialize.build_reducer/2>}

```

**Comment by sleipnir** [comment]
Apparently this has already been fixed by the last commits. We will reopen if necessary.
